name: Call Dagger functions

on:
  workflow_dispatch:

jobs:

  build:

    name: Call a Dagger function
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7


      - name: Call the Boilerplate Dagger function
        uses: dagger/dagger-for-github@6210aa04aaf743e52a7315449e213bb85cd828ce # v5.10.0
        with:
          version: "latest"
          verb: call
          module: github.com/staticaland/dagger-cog@main
          args: 'cog --file="README.md" --replace export --path="."'
